### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by dwillmer** [phosphorjs/phosphide#1]
# Aims

We are delivering a plugin-based application framework as part of PhosphorJS; the idea being that any application can be easily extended, statically or at runtime, by adding a new plugin.

This brings with it a range of issues, with front-end packaging being one of the most important. Unfortunately, front-end packaging in javascript is widely regarded as a minefield.

There are a number of options (the relevant ones are all discussed below), but in order to correctly frame the discussion we will start with the exact requirements for this project:

- The solution must be as spec-compliant as possible. [ES6 defines modules which can be dynamically loaded](http://www.ecma-international.org/ecma-262/6.0/#sec-modules); whichever solution we choose, we would like it to be as compatible as possible with the ES6 spec.
- The solution must preclude the possibility of multiple downloads of the same dependency.
- The solution must package multiple files, and multiple file types. A plugin will likely consist of js/css/images etc. We must be able to package them all.
- PhosphorJS is developed in [TypeScript](http://www.typescriptlang.org/), therefore builtin support for this would be nice, but is not a strict requirement.

# Existing solutions

## Browserify

[Node.js](http://nodejs.org) uses the `CommonJS` standard to import dependencies, however this isn't available in browser environments. [Browserify](https://browserify.org) alleviates this by bundling the code and its dependencies in a browser-compatible form.

- Using browserify for each plugin will result in each package/bundle incorporating its own version of any dependency. This means that we would potentially have the same dependency downloaded multiple times.
- Browserify doesn't package CSS/images by default, you need to use something like [the browserify-css plugin](https://www.npmjs.com/package/browserify-css)

## Require.js

[Require.js](http://requirejs.org) is a module loader which implements the `AMD` standard, and can be used to bundle your javascript files together.

- Require has [particularly strange behaviour](http://requirejs.org/docs/whyamd.html#commonjs) when it comes to commonjs support. tl;dr - `Use a server to translate commonjs modules to something usable in the browser`.

## npm / Node.js

Node is a non-browser runtime environment; it deserves a mention here because the built-in `npm` (apparently *not* Node Package Manager) is very widely used and has some nice features.

- NPM can package anything - css/html/js etc.
- One of node's main benefits (for development/server-side) is that is uses lots of small modules to maintain dependencies across the project. This allows different modules to use different, incompatible versions of a given library, but still allow pain-free development. This, however, is not appropriate for front-end deployment. We can't have incompatible versions of a library loaded - for example underscore/lodash/jquery/require all overload a global name (`_` / `$` / `require`). If multiple versions are loaded, one of them will over-ride the others.

## Component

[Component](https://github.com/componentjs/component) used to be a popular package management system, but it now openly declares itself as deprecated (just in case people think we're cherry-picking).

## Bower

[Bower](http://bower.io) is a package management system that can deal with javascript and non-javascript components.

- Is compatible with various module formats (AMD/commonjs etc).
- Has a flat dependency hierarchy, therefore can share dependencies between modules.
- Unfortunately there isn't really an advantage in using bower over npm.

## Volo

[Volo](http://volojs.org/) 

- Volo seems to be [built with AMD in mind](https://github.com/volojs/volo/wiki/Design-Goals), and although it claims it's not tied to AMD, we really want to be ES6 module compatible.
- Also from its [design goals document](https://github.com/volojs/volo/wiki/Design-Goals), it appears to want to deploy as a single javascript file, but it's not entirely clear.

## EnderJS

[EnderJS](http://enderjs.com) describes itself as `npm's little sister`, in that it's a way to manage your dependencies and build, but with a focus on the browser.

- The goals of the project seem very good; aiming for `small, loosely coupled modules`.
- Based on commonjs.
- The client API injects its own `$` namespace (a la jQuery), which seems like a *very* strange decision. Given that the `$` object is widely understood to be the jQuery object, this could cause confusion.

## Duo

[Duo](https://github.com/duojs/duo) is a package management system built on top of Component.

- Duo has a nice `zero-configuration` stance, whereby you don't need to add lines to a registry file.
- Unfortunately, Duo can't just extract the modules from one package and deploy as a different static module, like [[Webpack]] can.

## Webpack

[Webpack](http://webpack.github.io) describes itself as a `module bundler`, primarily designed to allow `code splitting` to facilitate large projects. Code splitting allows you to take a dependency hierarchy and deploy as a different set of static files to optimise loading times.

-  Webpack can do [hot module replacement (experimental)](http://webpack.github.io/docs/hot-module-replacement-with-webpack.html), [code splitting](http://webpack.github.io/docs/code-splitting.html), which are all very nice features.
- Unfortunately webpack [overloads `require`]() which could cause misunderstandings later with people who are used to the node behaviour.
- It doesn't support ES6 modules as standard, but [there is a plugin](https://github.com/babel/babel-loader) which can be used.

## System.JS / jspm (treated as a single item in this context)

[System.JS](https://github.com/systemjs/systemjs) pitches itself as a `Universal dynamic module loader`, in that it can load modules in any format, and deploy in the browser/NodeJS.

- It is spec-compliant - it is built upon the [ES6 Module Loader Polyfill](https://github.com/ModuleLoader/es6-module-loader), for which [ES6 compliance is an axiomatic goal of the library](https://github.com/ModuleLoader/es6-module-loader#es6-module-loader-polyfill-). This would allow us to simply drop System.JS as a dependency once browser ES6 support is sufficient.
- (As a result of the point above) System.JS has `System.import` support.
- It has built-in [TypeScript](https://github.com/Microsoft/TypeScript) support, which is beneficial for our development workflow as phosphorjs is written in TypeScript.

[jspm](http://jspm.io/) is a package manager built on top of SystemJS.

- Major advantage is that it therefore has all of the SystemJS support for multiple file formats.
- Has a flat, versioned dependency hierarchy, so it won't download multiple versions of a dependency.
- For development, it allows the compilation/transpilation to occur in the browser (even for plugins), and therefore allows a very quick edit-test cycle. Not a huge requirement for us, but a huge benefit nonetheless.
- Has typescript support through [this plugin](https://github.com/frankwallis/plugin-typescript), which has the added advantage of allowing us to *develop* in TypeScript without a compile step, as the transpilation and loading happens in the browser with System.JS.

## Steal.JS

[stealjs](http://stealjs.com) pitches itself as a `futuristic JavaScript dependency loader`; it is built on top of SystemJS, and includes tools for building and packaging on top of System.

- StealJS has a configuration system built on top of SystemJS, and therefore comes with all of the benefits of being able to deal with files in any format.
- StealJS [from this conversation](https://gitter.im/stealjs/steal/archives/2015/02/25) appears to have chosen to build on top of SystemJS, instead of using SystemJS directly, in order to facilitate `multi-main` or `progressively-loaded` sites. Since this is clearly possible without using StealJS, i'm not sure the additional overhead of StealJS is justified.

---

Given the requirements we have, my personal feeling is that SystemJS/jspm gives us the best spec-compliant system, with a decent deployment and development cycle.

**Comment by dwillmer** [comment]
Pinging @sccolbert @blink1073 @ellisonbg @jasongrout @jdfreder @Carreau @SylvainCorlay @rgbkrk @minrk

**Comment by ellisonbg** [comment]
Thanks for doing this study. I think the development workflow that npm offers us is really great, but it definitely doesn't solve the problems of how to get the code into the browser. 

Also, I very much agree that we can't rely on browserify for packages that are distributed/installed separately.

**Comment by sccolbert** [comment]
Browserify will also let us down when we want to dynamically load a package/plugin into an app which is already running. Certain libraries will not operate correctly if duplicate versions are loaded. We'll hit that issue with browserify. We'll definitely want a maximally-flat dependency system.

**Comment by rgbkrk** [comment]
Terrific writeup!

It would be nice to paint a few choices in terms of users of jupyter frontends (especially the notebook). There are several different interaction layers we have to think about, some of which are separate from this exploration itself but very inter related:

* How do library authors, those writing integrating directly with e.g. IPython, IHaskell, IRuby, IJulia, etc. to provide rich output specify an asset? What's the messaging protocol for that?
* Where do backend libraries install assets for loading? Are they installed per kernel?
* What path do they get served out of from the notebook?
* How easy is it to switch between using a remotely hosted version and a local copy?
* What gets serialized into formats like the notebook JSON?

/cc @parente @jtyberg @lbustelo @vinomaster

**Comment by ellisonbg** [comment]
We talked a bit about that today, recognizing the significant complexity in the different questions you are raising. This is especially true when these assets are provided by kernels, which may or may not be running on the same server as the main notebook.

Our initial answer was, wait for it....let's start with this level (how JS gets bundled, loading, deps resolved etc.) first and then tackle the next level up of how things are served served from and installed.

Ideally, we could specify everything at the API level by giving npm package names, and then *magically* have those loaded from whereever happens to know where they are (CDN, kernel, nb server, jspm). That will likely require a layer of abstraction that sits between the npm package names and resolvable URLs and the servers behind them, but I think we have to start to play around with the different options to see what patters they encourage/enable.

**Comment by rgbkrk** [comment]
The reason I bring them up is that they do affect the choices themselves. I'm all for playing with the options here, especially if we try to frame and apply it to how real users are wanting to take advantage of applications that will be dog fooding phosphor. Fill me in on whether this is about plugins for phosphor layout or if this has any bearing on jupyter output.

That being said, I agree with these goals/requirements for the project:

> The solution must be as spec-compliant as possible. ES6 defines modules which can be dynamically loaded; whichever solution we choose, we would like it to be as compatible as possible with the ES6 spec.
> The solution must preclude the possibility of multiple downloads of the same dependency.
> The solution must package multiple files, and multiple file types. A plugin will likely consist of js/css/images etc. We must be able to package them all.

Which currently sound "solved" by at least a few of these, including `jspm` and `webpack`. What's the layer above going to be? Is that what's being solved here?

It seems from other chatter, people are leaning towards `jspm` which is looking decent. It's nice that we can straddle current requirejs and other packages. The first big test would be attempting what @jdfreder did in https://github.com/jupyter/notebook/pull/268.

The only rough edges I've noticed so far are that when specifying `System.import('npm:<package_name>').then(...)` there doesn't seem to be a way to specify the version number. I'm assuming in most contexts, we'll be loading relative to the server itself which negates much worry over that (though people will be really happy to be able to pull common packages directly).

**Comment by ellisonbg** [comment]
> The reason I bring them up is that they do affect the choices themselves.
> I'm all for playing with the options here, especially if we try to frame
> and apply it to how real users are wanting to take advantage of
> applications that will be dog fooding phosphor. Fill me in on whether this
> is about plugins for phosphor layout or if this has any bearing on jupyter
> output.
>
Ideally both.

The various jupyter components we are building as npm packages need a clean
way to get loaded into our web app - that still allows dependencies to be
resolved globally by later install and loaded things. Other browser based
apps building on top of npm will face the same types of challenges.
Definitely not a phosphor specific challenge.

The nicely npm-packaged lightning repos of the @freeman-lab are a great
example. The npm side is wonderful, but the final browserify step only
works as long as the separate browserified bundles don't have overlapping
dependencies. I know you know all of this stuff - I only bring it up to say
that pretty much all the stuff we are doing and thinking about, whether
thebe style HTMl pages, live notebooks or widget dashboards have the same
problem of loading npm package onto the page. So at the first level, this
is attempt to just get clarity and consensus about the code-loading stuff,
just like we did on using npm to package things.

The notion of a phosphor plugin adds another layer to this picture in terms
of runtime dependecies. For example, a file browser plugin in the jupyter
web app needs a live and hooked up ContentManager. Just throwing the
jupyter-js-service on the page is not enough. Part of the reason we have
struggled so much with require.js is that we use it both for code loading
and runtime dependencies. The phosphor plugin abstraction will cleanly
express both the code loading and runtime dependency aspects. It will,
necessarily sit on top of whatever decisions we make about code-loading.

Obvious, if someone wants to use an npm based jupyter component without
phosphor plugins, it still makes sense to try and standardize on the
code-loading part of it.

But I should clarify the intention of starting this discussion - we desire
the decision reached here to apply to both phosphor and jupyter. I will
start a thread on the jupyter list to clarify this point...

That being said, I agree with these goals/requirements for the project:
>
> The solution must be as spec-compliant as possible. ES6 defines modules
> which can be dynamically loaded; whichever solution we choose, we would
> like it to be as compatible as possible with the ES6 spec.
> The solution must preclude the possibility of multiple downloads of the
> same dependency.
> The solution must package multiple files, and multiple file types. A
> plugin will likely consist of js/css/images etc. We must be able to package
> them all.
>
> Which currently sound "solved" by at least a few of these, including jspm
> and webpack. What's the layer above going to be? Is that what's being
> solved here?
>
> It seems from other chatter, people are leaning towards jspm which is
> looking decent. It's nice that we can straddle current requirejs and other
> packages. The first big test would be attempting what @jdfreder
> <https://github.com/jdfreder> did in jupyter/notebook#268
> <https://github.com/jupyter/notebook/pull/268>.
>

I know you have your ear to the JS-tracks so that is helpful feedback. On
the surface, jspm does look nice.


> The only rough edges I've noticed so far are that when specifying
> System.import('npm:<package_name>').then(...) there doesn't seem to be a
> way to specify the version number. I'm assuming in most contexts, we'll be
> loading relative to the server itself which negates much worry over that
> (though people will be really happy to be able to pull common packages
> directly).
>
Yes, at that level it becomes an installation question.

—
> Reply to this email directly or view it on GitHub
> <https://github.com/phosphorjs/phosphide/issues/1#issuecomment-147561026>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by dwillmer** [comment]
Thanks for chipping in Kyle, much appreciated!

With regards to the versioned dependencies, my understanding is that the System.config (top-level) would be set like:

```
System.config({
  "map": {
    "jquery": "github:components/jquery@^2.1.1"
  }
});

System.config({
  "versions": {
    "github:components/jquery": "2.1.1"
  }
});
```

which was taken from [this post by Jack Franklin](http://javascriptplayground.com/blog/2014/11/js-modules-jspm-systemjs/).

**Comment by lbustelo** [comment]
Anyone looked at https://wiki.eclipse.org/Orion? Wondering if there is anything to learn there.

**Comment by blink1073** [comment]
I would suggest that we use `systemjs` directly.  `jspm` does not appear to add anything that `npm` cannot provide, in that you can pull from a Github repo (including a commit hash) using `npm`.  Also, `jspm` hijacks the `package.json` file and the file hierarchy of where the node modules are stored, which would not allow other tools (like `TypeScript`), to locate the node modules in their standard locations.

**Comment by dwillmer** [comment]
@lbustelo Thanks, hadn't seen Orion, but it's good to know about it.

**Comment by mathisonian** [comment]
Hey all, I'm still trying to wrap my head around all of this but here are some scattered thoughts:

* `npm` is the current standard for hosting javascript (front & backend) packages, whether they are loaded with `browserify`, `webpack`, `systemjs`, or other
* it may be useful to note the distinction between module format and distribution format (i.e choosing between common.js + es6 modules vs choosing between systemjs and webpack)
* it isn't clear to me whether phosphorjs modules are only meant to be used inside the phosphorjs ecosystem or if they should work standalone as well (and it seems like phosphorjs might be shipping a custom server for on demand bundling?)
* check out https://wzrd.in/ as an example of an open source server that makes on demand bundles of modules from npm (including specific versions)
* "The solution must preclude the possibility of multiple downloads of the same dependency" - I would think hard about the pros/cons of this. correct me if I'm wrong but essentially it means that the server making the bundles needs to understand the current state of the bundle on the client -- and the client should be able to request arbitrary phosphorjs plugins at any time? this seems like a significant amount of complexity. what about the case of different versions of the same library? 
* its always good to look at what other large js projects are doing. Facebook is one of the strongest open source javascript organizations right now and they are strong advocates of ES6 + Webpack.

**Comment by sccolbert** [comment]
PhosphorJS modules are written using the ES6 module format, but are currently compiled down to CommonJS and distributed like a normal Node package. In our examples, we use Browserify to bundle everything, but that's just an implementation detail of the example.

We have no plans to ship a custom server as part of PhosphorJS.

> The solution must preclude the possibility of multiple downloads of the same dependency

The exception to this is different versions of the same library (though that should really be avoided). Some libraries will simply not work properly if more than one version of the library is loaded, because each version maintains its own internal state and passing objects across the version boundaries is not guaranteed to work. React is an example of such a library. Certain PhosphorJS libraries have the same restriction.

**Comment by sccolbert** [comment]
For those that may not know, a high-level overview of PhosphorJS can be found here: http://phosphorjs.github.io/

**Comment by jdfreder** [comment]
> The only exception to this is different versions of the same library (though that should really be avoided).

I don't think people would ever do that intentionally.  It just becomes a problem with sub-dependencies.

**Comment by sccolbert** [comment]
> I don't think people would ever do that intentionally. It just becomes a problem with sub-dependencies.

Right. This is something that Bower nevertheless explicitly disallows. When using Bower, you cannot have multiple versions of the same library, period. I think there is merit to this line of thinking, especially on the front-end. I'm not sure whether we should be *as* regimented, but it would probably help head-off a certain class of bugs.

**Comment by rgbkrk** [comment]
> I don't think people would ever do that intentionally. It just becomes a problem with sub-dependencies.

The explicit counterexample to me is two different library authors writing output in the notebook, whether in the same cell or different cells. Users face this collision all the time without them knowing what's going on.

**Comment by ellisonbg** [comment]
Yep (although still not intentional on the library authors or users part).

On Tue, Oct 13, 2015 at 9:39 PM, Kyle Kelley <notifications@github.com>
wrote:

> I don't think people would ever do that intentionally. It just becomes a
> problem with sub-dependencies.
>
> The explicit counterexample to me is two different library authors writing
> output in the notebook, whether in the same cell or different cells. Users
> face this collision all the time without them knowing what's going on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phosphorjs/phosphide/issues/1#issuecomment-147900349>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
I just finished playing with [stealjs](http://stealjs.com/), and I believe it offers everything we need.  

- It adds auto-configuration on top of SystemJS, freeing us from configuring every single npm module.
- Unlike jspm, it preserves the existing `node_modules` (and `bower_components`) file structure.  This allows it to play nicely with other existing tools like the TypeScript compiler.
- It seamlessly loads ES6, CJS, and AMD syntax modules.

**Comment by dwillmer** [comment]
+1, given the point about `node_modules`, that's a big win over jspm

**Comment by ellisonbg** [comment]
Can you describe what the auto-configuration exactly does and what the
alternative is?

On Wed, Oct 14, 2015 at 5:43 PM, Dave Willmer <notifications@github.com>
wrote:

> +1, given the point about node_modules, that's a big win over jspm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phosphorjs/phosphide/issues/1#issuecomment-148210816>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
`SystemJS` has configuration options, including `path` (similar to `requirejs`).  `steal.js` parses your `package.json` and creates all of these configuration paths for you, mangling the names of dependency packages to include the version string.  

A plugin can be loaded as an npm package in `node_modules`, and `steal.js` will load those files from that location.  Relative urls are mangled to include the correct path to the sub-package, including image urls in CSS.  

Semver is preserved, and if one plugin requires a dependency that has already been met, it uses the name-mangled version of that dependency that has already been loaded.  This includes when the "core" package is bundled using `steal.js`, and another package is loaded dynamically.  

Notes: 
- When not bundled, the entire npm package structure is traversed (all of the `package.json` files are loaded and parsed).  This process failed when I had `karma` listed as a dependency, but could be worked around using the `npmIgnore` configuration option in `steal.js`.  I will be looking into that problem further.
- We chose to allow the `import foo.css;` format, to preserve compatibility with `browserify-css`, since there is no established loader syntax for non-JS files in ES6.

**Comment by sccolbert** [comment]
The karma loading is probably failing because karma relies on builtin node functionality, which is obviously missing in a browser. This should be a non-issue for node modules which don't depend on node built-ins. If we need to shim node built-ins, we can: https://github.com/stealjs/system-npm/issues/61#issuecomment-107420230, though I would prefer to not do that by default.

**Comment by sccolbert** [comment]
@blink1073 Can you please provide a summary of what we discussed during the week and our plans for moving forward wrt to NPM/SystemJS/StealJS.

**Comment by blink1073** [comment]
SystemJS loads ES6 modules, AMD, CommonJS and global scripts in the browser and NodeJS, without requiring any prior translation.  As opposed to WebPack, it is based on the ES6 Standard.  It uses regexes to determine the type of module prior to loading.  It is available now for use as a polyfill.

SystemJS requires configuration similar to RequireJS (e.g. paths), but this can be mitigated with either `jspm` or `steal.js`.  `jspm` suffers from being “another package manager” on top of `npm`, requiring installation using `jspm install`, and using non-standard file locations.  

`steal.js` uses standard `npm install` semantics, allowing both developers and users to use `npm` workflows.

Plugin authors provide an `npm` package, to be installed by the user via `npm install`.  `steal.js` will automatically resolve the imports by crawling (fetching) the `package.json` files and setting up the SystemJS config accordingly, using name-mangled paths with the package version string.  

`steal.js` respects SemVer, meaning that if it has already loaded a module meeting a requirement, it will use the client-side module again.  

We can use the suffixed imports in user-space as well, enabling us to use `System.import(‘bqplot#^1.0.4’)` to get a particular version.

Neither plugin authors nor users need to be aware of the existence of `steal.js`, unless they want to use a suffixed import.  

Relative links to images in CSS are automatically name-mangled to the appropriate path.

If desired, we can use `steal-builtins` to provide the node module polyfills that browserify provides.

`steal.js` is under active development (562 forks), and the lead maintainer appears to be quite responsive.

The main application can be shipped with a `node_modules` hierarchy checked-in, allowing users without `npm` to have a base set of functionality.  They can then use `npm` to install further plugins.
