### ISSUE TITLE
Command Palette Fuzzy Matching

### ISSUE THREAD

**Issue by dwillmer** [phosphorjs/phosphide#16]
As part of the command palette work, we're going to need to perform fuzzy matching on user inputs. This issue is for discussing the various packages available / whether we should write our own.

# fuzzy

[[https://www.npmjs.com/package/fuzzy]]
[[https://github.com/mattyork/fuzzy]]

```
npm install --save fuzzy
```

Summary - seems simple to set up and use, but also lacking the more advanced features in other packages:

```javascript
var fuzzy = require('fuzzy');
var data = ['alpha', 'altitude', 'alien', 'bob'];
var results = fuzzy.filter('al', data);
var matches = results.map(function(el) { return el.string; });
console.log(matches); // ['alpha', 'altitude', 'alien']
```

allows you to wrap the matching characters with `pre` and `post` tags
(eg, in order to highlight the matching characters):

```javascript
var data = ['alpha', 'altitude', 'alien', 'bob'];
var options = { pre: '<b>', post: '</b>' };
var results = fuzzy.filter('al', data, options);
console.log(results);
```
gives
```
[
  {string: '<b>al</b>pha', index: 0, score: 2, original: 'alpha'},
  {string: '<b>al</b>titude', index: 1, score: 2, original: 'altitude'},
  {string: '<b>al</b>ien', index: 2, score: 2, original: 'alien'}
]
```
It also allows you to provide a function for extracting the string to search
from an object:
```javascript
var items = [{the_string: 'alien'}, {the_string: 'bob'}];
var options = {
  extract: function(el) { return el.the_string; }
};
```
however, it doesn't appear to support levenstein distance or custom routines:
```javascript
var data = ['alpha', 'alps'];
fuzzy.filter('alpi', data); // empty array returned
```

It also *does* have a case-sensitivity option, but it's not documented on the front page, or used in the examples, and requires searching through the code in order to find it. not a good impression for the feature most people will want to try/set for the simple searches.

# fuzzysearch-js

[[https://www.npmjs.com/package/fuzzysearch-js]]
[[https://github.com/unlooped/FuzzySearchJS]]

seems more complicated to set up and use, but allows easy customisation of the search routines, and includes a module system to use pre-packaged modules
for the more advanced searches, such as levenstein distance:

(this example taken directly from the npm/github front page)
```javascript
var FuzzySearch = require('fuzzysearch-js');
var levenshteinFS = require('fuzzysearch-js/js/modules/LevenshteinFS');
var indexOfFS = require('fuzzysearch-js/js/modules/IndexOfFS');
var wordCountFS = require('fuzzysearch-js/js/modules/WordCountFS');

var data = ['Hydrogen','Helium','Lithium','Beryllium'];

var fuzzySearch = new FuzzySearch(data, {'minimumScore': 300});
fuzzySearch.addModule(levenshteinFS({'maxDistanceTolerance': 3, 'factor': 3}));
fuzzySearch.addModule(indexOfFS({'minTermLength': 3, 'maxIterations': 500, 'factor': 3}));
fuzzySearch.addModule(wordCountFS({'maxWordTolerance': 3, 'factor': 1}));

var result = fuzzySearch.search('Hlium');
console.log(result);
```
returns
```
[ { score: 590,
  details: [ [Object], [Object], [Object] ],
  value: 'Helium' },
{ score: 340,
  details: [ [Object], [Object], [Object] ],
  value: 'Beryllium' } ]
```
This is quite a bit of extra setup, but gives a lot of configurability.

The whole system revolves around a general score which is calculated from the scores
after running all the added modules. This appeals to me as we can add our own
modules, or just tweak the scoring system to suit our own needs.

Negatives: There's no performance benchmarks, and the tests aren't comprehensive.

# fuzzy-filter

[[https://www.npmjs.com/package/fuzzy-filter]]
[[https://github.com/stratuseditor/fuzzy-filter]]

```javascript
var fuzzy = require('fuzzy-filter')
fuzzy("alp", ["altitude", "alps"]) // ["alps"]
```

Supports case insensitive searches, and orders the results nicely, but is
quite simplistic and doesn't include a full scoring system like fuzzysearch-js. 

# fuzzaldrin

[[https://www.npmjs.com/package/fuzzaldrin]]
[[https://github.com/atom/fuzzaldrin]]

The fuzzy matcher written for Github's Atom editor. Seems fairly good - has
separate scoring and filtering modules, and returns decent results.

Negatives - a lot of the 'internals' are very hard-coded. For example in the
scorer module, there's lines like:

```coffeescript
if indexInString is 0 or ...:
  characterScore += 0.8
```

clearly scoring works along these lines, but there's no way to tweak the `0.8`
in this case, without just copying the whole module - it's not been written 
to be configurable. On the other hand, these values are probably hand-tweaked
for a code editor, so they might be useful to us.

Fuzzaldrin also has a benchmark setup (`npm run benchmark`), which is a very
good sign.

In general i think that it's a suitable module, but the hard-coding is a huge negative.
Also, being part of Atom means it's written in CoffeeScript, which is just terrible.

# Summary

In general, I think fuzzysearch-js is the best candidate as it's modular and
extensible.

Atom's fuzzaldrin is also a good contender, and is the only package to have usable
benchmarks, but the hard-coding is worrying.

**Comment by blink1073** [comment]
I'd say use `fuzzysearch-js`, and just copy the benchmark from `fuzzaldrin` if we're concerned about that.

**Comment by afshin** [comment]
Because searches happen on user input and aren't a background part of our system, I think performance is going to be a non-factor.

I agree, re: `fuzzysearch-js`. It looks the most appropriate of these.

**Comment by sccolbert** [comment]
performance is something we need to keep in mind. We have ~16ms (30ms conservatively) to perform the match and update the DOM. This will be searching on the order of ~500 string worst case.

`fuzzysearch-js` hasn't been updated in a while, but the code is pretty clean. Haven't looked at the others yet.

**Comment by dwillmer** [comment]
Here's a quick performance comparison - code is here: https://gist.github.com/dwillmer/422c894022153d673df7

word list is the 109,582 english words from here: http://www-01.sil.org/linguistics/wordlists/english/wordlist/wordsEn.txt

Search: 'aa' (average of 3)
```
fuzzy: 84ms
fuzzysearch-js: 429ms
fuzzyfilter: 22ms
fuzzaldrin: 63ms
```

However, this is slightly unfair on fuzzysearch-js because it is doing more work (ie, this is not a like-for-like comparison). Removing the levenstein distance calculation from fuzzysearch-js gives this:

(average of 3)
```
fuzzysearch-js: 125ms
```
so it's still the slowest in this benchmark, but it's now a reasonable comparison.

Changing the search term to 'beleagu', which should return 4 items from ~110,000:

(average of 3)
```
fuzzy: 70ms
fuzzysearch-js: 218ms
fuzzyfilter: 20ms
fuzzaldrin: 60ms
```
So it appears that `fuzzyfilter` is the fastest of the four, and `fuzzysearch-js` is the slowest by quite some margin.

The final test is with a restricted data set (250 items), which is much more like the data size we will expect for the phosphide command palette:

Search: 'abori' (average of 3)
```
fuzzy: 2ms
fuzzysearch-js: 4ms
fuzzyfilter: 1ms
fuzzaldrin: 3ms
```

Search: 'aa' (average of 3)
```
fuzzy: 3ms
fuzzysearch-js: 4ms
fuzzyfilter: 1ms
fuzzaldrin: 3ms
```

So the overall hierarchy hasn't changed, `fuzzysearch-js` is still the slowest, and `fuzzyfilter` is still the fastest, however all results are well within our idealised 16ms time envelope. With this in mind, I suggest that we go with `fuzzysearch-js` initially, purely due to the extensibility/scoring mechanisms, and if we see any performance issues, then we can decide whether to change to one of the others.

**Comment by afshin** [comment]
:+1:

**Comment by dwillmer** [comment]
Repeated for @sccolbert 's worst case of 500 items:

Search 'aa' (average of 3)
```
fuzzy: 3ms
fuzzysearch-js: 6ms
fuzzyfilter: 1ms
fuzzaldrin: 2ms
```

Search 'abori' (average of 3)
```
fuzzy: 3ms
fuzzysearch-js: 5ms
fuzzyfilter: 1ms
fuzzaldrin: 2ms
```

**Comment by blink1073** [comment]
Yep, I'd say the added power is worth it if we're below the time budget.

**Comment by sccolbert** [comment]
Thanks for the benchmarks!

**Comment by sccolbert** [comment]
I'm okay with your pick here, provided it doesn't leak into the public API. i.e. make sure we can swap for another matcher whenever we need to.
