### ISSUE TITLE
Plugin Definitions

### ISSUE THREAD

**Issue by dwillmer** [phosphorjs/phosphide#2]
# Aims

This is a discussion about the *definition* of plugins for the Phosphide framework.

How will we:

- define modules / entry points / general code files?
- other resources such as CSS/images?
- use a folder/file hierarchy?

# Existing plugin systems

## Eclipse (different to Java)

Eclipse is one of the most widely used and recognised plugin systems around. To declare a plugin with Eclipse you need to declare a plugin manifest file (XML), which gives some general housekeeping information, such as a unique plugin ID, plugin version, name, location of the runtime, and plugin dependencies.

It's quite nice to have this information separate from the actual code, and means that items such as dependency hierarchies can be built before loading the actual plugins.

The location of the runtime is a single jar file.

### Extender plugins

Extender plugins allow you to add specific items into a running application without actually loading the full plugin. An example of this could be adding menu items into an application, but only loading the plugin when they're clicked.

This is a nice feature, and also sits nicely in the declarative nature of the manifest file.

### Items in the runtime

The main plugin runtime file may define classes such as

```java
import org.eclipse.core.runtime.IExecutableExtension;

public class MyClass implements IExecutableExtension {
  ...
}
```

which then become available to other components/extensions/plugins once the plugin runtime is loaded.

## Java

Java has had plugins since version 1.0. These early versions just separated the JVM libraries as 'trusted' code, and plugins as 'untrusted' code, with plugins always loaded through PluginClassLoaders, so they can't access the filesystem or network.

The class loader restrictions were considered a serious bottleneck, as code needed to be updated in lots of places if you updated an API or changed permissions. As a result, Java version 2.0 implemented declarative permissions using a Permissions class, which only requires updating a single object when permissions change.

## Oracle

Oracle has a [plugin framework for their databases](https://docs.oracle.com/cd/E24628_01/doc.121/e25161/define.htm#EMPRF11233). Each plugin has a metadata file (XML), which is similar in concept to the Eclipse manifest file. This file contains the unique plugin ID, the plugin version, and a list of dependencies, which are plugin IDs and versions.

There is also [a second metadata file](https://docs.oracle.com/cd/E24628_01/doc.121/e25161/define.htm#EMPRF11246) (plugin_registry.xml) which contains further information `required by the Management Agent that the plugin will be deployed to`. This includes items such as the location of the runtimes, which are all included in the single manifest file in the Eclipse system.

Oracle also ships an `Extensibility Development Kit` which includes tools to validate the plugin definition files, which is a nice idea. There is also a plugin builder to allow development without hand-coding XML.

## Sublime Text

[Sublime](http://www.sublimetext.com/) has nominally-typed plugins (python-based) with a useful but fairly static set of capabilities. For example, the base plugin class (sublimeplugin.Plugin) has onSelectionModified(view). This is called after the selected text has changed in a view, which is fine for sublime, but not really suitable for a generic application framework.

Sublime's API also deals with different object required by plugins by [having run() overloaded with different signatures](https://www.sublimetext.com/docs/api-reference#sublimeplugin.TextCommand). Again, this is fine for Sublime, but doesn't scale well. Not only that, but given that TypeScript is a superset of javascript, we can't support 'normal' function overloading, which quickly becomes unwieldy.

## Electron

[Electron](http://electron.atom.io/) at a low level [uses the blink plugins (C++)](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/plugins/PluginView.h), at a higher level (js) it has [rudimentary support for chrome://plugins](https://github.com/atom/electron/blob/357dea506aeb095e67466848a5c9803e03096f80/docs/tutorial/using-pepper-flash-plugin.md). 

## Blink

As per the example above, it uses nominal typing for the various plugin functionalities. Seems like a good fit for C++, but it means there's a lot of code to write to implement basic things.

## Firefox

The Firefox browser has a plugin system (Mozilla calls them 'add-ons'), [most of the definition details can be found here](https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/The_Essentials_of_an_Extension).

Plugins are deployed as zip files, but with a custom .XPI extension (so that the browser knows they are to be executed). At the top level in the zip file is an `install.rdf` file ([see RDF format here](https://en.wikipedia.org/wiki/Resource_Description_Framework)), used to declare the metadata for the plugin. This is the equivalent of the manifest file in Eclipse. It contains a unique identifier for the plugin, in addition to a human readable name, a description field, version, creator and URL.

- The RDF format is being replaced with a description format which is simpler, as it is deemed too complex.
- A nice feature in the existing RDF format is that you can define localization changes, for example:

```
<em:description>Welcome to XUL School!</em:description>
```

can be represented as:

```
<em:localized>
  <Description>
    <em:locale>es-ES</em:locale>
    <em:name>XUL School Hola Mundo</em:name>
    <em:description>Bienvenido a XUL School!</em:description>
  </Description>
</em:localized>
```

for Spanish users, which will get picked up based on the locale set in the rest of the page/application. A [more in-depth example can be found here](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_extension_descriptions#Localizing_before_Gecko_1.9).

It is also possible to define static strings for the entire plugin in .dtd files within locale folders, in order to show language-specific changes across all new UIs.

## Chrome

Google Chrome has the metadata defined in a `manifest.json` file at the top level of the plugin directory, [manifest format definition is here](https://developer.chrome.com/extensions/manifest). A small, but important difference here is that Chrome clearly defines the following three fields as required:

```json
{
  "manifest_version": 1,
  "name": "My Plugin",
  "version": "versionString"
}
```

Adding the manifest format version to the file is a nice addition, and is definitely something we should consider to make upgrading easier.

Chrome also packages its plugins as zip files with a custom (.crx) extension, but the zip file needs to be signed.

# Summary

Most of the major plugin frameworks have a declarative `manifest` file to define metadata such as a unique ID, version, name, description and (optionally) localization for the description. This seems like a good idea, and having an arbitrary length list of localizations is also something we should consider.

I suggest using JSON as the declarative language for the manifest, along the lines of:

```javascript
// manifest.json
{
  "id": "my unique ID",
  "version": "0.1",
  "name": "My Plugin",
  "description": "This is a plugin",
  "content": "content/plugin.js", // the runtime.

  "locales": { // optional
    "es-ES": {
      "name": "Spanish name...",
      "description": "Spanish description..."
    },
    "de-DE": {
      "name": "German name...",
      "description": "German description..."
    }
  }
}
```

This implies a folder structure along the lines of:

```
mypluginfolder/
├── manifest.json
└── content
     └── plugin.js
```

for a simple plugin. The content folder can include any other required folders/files such as CSS/HTML/images. 

## Questions

- Do we want 'trusted' and 'untrusted' code like Java plugins? This affects our design as untrusted code needs class loaders to sit between the app and the plugins. Essentially this boils down to `do we want to permission anything on the plugins?`.
- I suggest we don't want a Blink/Sublime-esque system where the plugins are individual specific commands with their own run method. I think a plugin should be able to extend a application in a number of ways:

```typescript
interface IPlugin {
  
  /**
   * Registers a plugin with an application, but does not load
   * or execute any code.
   *
   * This would be useful if, for example, you wanted to have plugins
   * stored on a remote server, with the user able to turn them on without
   * loading the code unless it's required.
   * (This is also possible with a delayed import in ES6)
  register(): string;

  /**
   * Actually load a plugin in the given application
   */
  load(app: IApplication): void;

  /**
   * Unload plugin from the given application
   */
  unload(app: IApplication): void;

  /**
   * The next few lines are examples of two overlapping systems which we
   * might want to think about.
   *
   * Firstly, there's the application components that a lot of plugins
   * will want to add, such as new commands, menu items and keymaps.
   * These could be implemented as shown below as their own dedicated
   * APIs.
   *
   * Alternatively we could declare a `pluggable` interface as shown by
   * pluggables(), which allows any pluggable part of the system 
   * (including commands/menu items/keymaps) to be set by the list of 
   * pluggable objects.
   */
  commands: ICommand[];
  menuItems: IMenuItem[];
  keymaps: IKeyBinding[];

  pluggables: IPluggable[];
}
```

We could implement IPluggable as

```typescript
interface IPluggable {
  location: string;
  value: any
}
```

So a simple usage example could be: 

```typescript
  get pluggables: IPluggable[] {
    return [
      {
        name: 'app-icon',
        value: 'icons/my-custom-plugin-icon.png'
      }
    ];
  }
```

Clearly this requires somewhere in the application that's already registered under the name 'app-icon', so the application knows where this value should be set.

My main idea for registering places in the application for pluggable behaviour is to extend the [phosphorjs attached properties](https://github.com/phosphorjs/phosphor-properties) to be pluggable which (once implemented) could look like:

```typescript
  appIconProperty = new PluggableProperty<Model, string>({
    name: 'app-icon'
    value: 'default-phosphor.png'
  });

  get appIcon(model: Model): string {
    Model.appIconProperty.get(model);
  }

  set appIcon(model: Model, value: string): void {
    Model.appIconProperty.set(model, value);
  }
```

where the `name` attribute in the object passed into PluggableProperty causes the application to register this particular property as 'pluggable' via 'app-icon'.

### Positives

- Simple attributes across the application are easily pluggable without subclassing / knowing much about the application you're modifying. This is a very important point, as we want to minimise the required knowledge (barrier to entry) to modifying an existing codebase.
- I would argue that attached properties (with small modifications like this) are a nice pattern to follow to make large sections of the application pluggable by default.

### Negatives

- Lots of things are set with strings, and `any` seems to be the best fit for the value type.

### Integrating with an App

- We'll also want any pluggable to return a disposable when it gets set, so that we can remove *or revert* a setting if a plugin does get stopped.
- My personal feeling is that we don't want the plugins to deal with the disposables; I would like to see the plugins hand their lists of pluggables to the application, and then when they are disposed of (by the application/plugin manager), the plugin is disposed of through the IDisposable interface that it provides. This avoids the possibility that a plugin writer could forget to cleanup on shutdown, which could for example accidentally leave broken menu items in an app.
- I think Eclipse gets a lot of things right, but [another major advantage of TypeScript is the structural typing](http://blogs.msdn.com/b/typescript/archive/2013/01/24/interfaces-walkthrough.aspx), which means we don't need to force users to import any phosphor components in order to correctly implement a plugin interface, like you would need with any `IFunction` / `IExecutableExtension` in Eclipse.

**Comment by dwillmer** [comment]
Pinging @sccolbert @blink1073 @ellisonbg @jasongrout @jdfreder @Carreau @SylvainCorlay @rgbkrk @minrk

**Comment by jdfreder** [comment]
> I suggest using JSON as the declarative language for the manifest, along the lines of:

I don't see any reason to create a custom manifest file if we continue to use npm, it's just reinventing the wheel.   If there's additional info you need to store you can add it to package.json http://stackoverflow.com/questions/10065564/add-custom-metadata-or-config-to-package-json-is-it-valid .

> Do we want 'trusted' and 'untrusted' code like Java plugins? This affects our design as untrusted code needs class loaders to sit between the app and the plugins. Essentially this boils down to do we want to permission anything on the plugins?.

This is a really cool idea.  I could see this opening the door for the possibility, in the distant future, to allow notebooks to package embedded plugins.  /me scratches head/ not sure what that really entails, but it sounds cool!

**Comment by sccolbert** [comment]
Yeah, if we stick with NPM, we can just add data to `package.json`. This is something which is explicitly recommended: http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

**Comment by dwillmer** [comment]
Sounds good, we'll just take the manifest ideas and put them in the package.json, maybe with a `_phosphor_` prefix.

**Comment by rgbkrk** [comment]
That's effectively what Atom does, though it has a reduced surface. Here's an example package:

```
{
  "name": "phossy",
  "main": "./lib/phossy",
  "version": "0.0.0",
  "description": "A short description of your package",
  "keywords": [
  ],
  "activationCommands": {
    "atom-workspace": "phossy:toggle"
  },
  "repository": "https://github.com/rgbkrk/phossy",
  "license": "MIT",
  "engines": {
    "atom": ">=1.0.0 <2.0.0"
  },
  "dependencies": {
  }
}
```

**Comment by dwillmer** [comment]
I deliberately left Atom out of the list above to simplify the discussion, but it's worth mentioning (@sccolbert nudged me to mention it :) ) - Atom uses the [`Service Locator` pattern](https://en.wikipedia.org/wiki/Service_locator_pattern) which is another way to decouple components in a large system.

We are going to need to make a decision about the pattern(s) we want to use in the phosphor-plugins. `Service Locator` is nice as it decouples the calling of various functions from the implementation in a similar way to the [`Singleton` pattern]() but [without the drawback that the unique class needs details about the service it implements](http://gameprogrammingpatterns.com/service-locator.html). This is an important distinction, however the drawback is that this complete decoupling of sender and consumer can result in more difficulty debugging.

Specifically, it is possible to end up with run-time errors instead of compile-time errors (even with statically-typed code), because of the complete decoupling in the `Service Locator` pattern. See [here](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/) and [here](http://www.popkram.com/blog/2013/02/one-reason-why-i-dont-like-service-locator/) for some sound reasoning against this pattern.

We can contrast this with [an Eclipse-style plugin system based around 'extension points'](https://wiki.eclipse.org/FAQ_What_are_extensions_and_extension_points%3F), which allows a lower level of decoupling, but without the inherent risks of Service Locator. 

Given that we are going to be working in an ecosystem made up of TypeScript and javascript (important because js won't be forced to adhere to interfaces declared in ts files), we feel that a system based on extension points provides a clearer development and debugging experience, without losing any of the functionality we care about.

**Comment by sccolbert** [comment]
This is a recap of our current thoughts on the matter.

The declarative *definition* of a plugin will be specified in the `package.json` under the `"phosphide"` key. The value of that key will adhere to the following interface(s):

```typescript
interface IPluginJSON {
  /**
   * The path to the "main" javascript file for the plugin.
   *
   * This path is relative to the `package.json`.
   */
  main: string;

  /**
   * The extension points provided by the plugin.
   *
   * Other plugins may contribute extensions to these extension points.
   */
  extensionPoints?: IExtensionPointJSON[];

  /**
   * The extensions provided by the plugin.
   *
   * These are contributions to extension points of other plugins.
   */
  extensions?: IExtensionJSON[];
}


interface IExtensionPointJSON {
  /**
   * The unique id of the extension point.
   *
   * This should be namespaced: "my-plugin:extension-point-name".
   */
  id: string;

  /**
   * The name of the receiver function in the plugin `main` module.
   *
   * When an extension is loaded for this extension point, this
   * function will be invoked with an `IExtension` object.
   */
  receiver: string;
}


interface IExtensionJSON {
  /**
   * The id of the extension point to which the extension contributes.
   */
  point: string;

  /**
   * The name of the loader function in the plugin `main` module.
   *
   * When the extension is loaded, this function will be called to
   * return a Promise which resolves to the actual extension object
   * to contribute to the extension point.
   */
  loader?: string;

  /**
   * The path to the JSON data file for the extension.
   *
   * Some extension points (like menus and keymaps) can make use of
   * data defined as JSON. This path will be used to load the JSON
   * and provide it to the extension point.
   */
  data?: string;

  /**
   * Extra configuration data for the extension.
   *
   * Some extension points can make use of extra static declarative
   * data associated with an extension. That data goes here in the
   * form of a JSON object.
   */
  config?: any;
}
```

An extension point is defined in two parts:
1. The type of extension object expected by the extension point.
2. The receiver function which accepts the extension.

The definition of an actual extension object is defined by Phosphide as:

```typescript
/**
 * The interface for an extension (defined by Phosphide).
 */
interface IExtension<T> {
  /**
   * The actual extension object.
   *
   * This is the result of resolving the Promise returned by
   * the loader function specified by the extension JSON.
   *
   * This will be `null` if the extension does not specify a loader.
   */
  object: T;

  /**
   * The loaded JSON specified by the extension.
   *
   * This is the result of calling `JSON.parse` on the data file
   * specified by the extension JSON.
   *
   * This will be `null` if the extension does not specify a data file.
   */
  data: any;

  /**
   * The config specified by the extension.
   *
   * This will be the object representation of the config specified
   * in the extension JSON.
   *
   * This will be `null` if the extension does not specify a data file.
   */
  config: any;
}
```

A receiver function is defined in the plugin `main` module and has the following signature:

```typescript
/**
 * Some user-defined extension object interface.
 */
interface IFoo {
  // ...
}


/**
 * The receiver function for the `my-project:foo` extension point.
 *
 * The receiver should take appropriate action for hooking up the
 * extension, and return a disposable to reverse those affects.
 *
 * The disposable will be called by Phosphide when the plugin
 * which contributed the extension is unloaded.
 */
function receiveFoo(extension: IExtension<IFoo>): IDisposable {
  // ...
}
```

The loader function defined by the extension would be as follows:

```typescript
/**
 * The loader function for the `my-project:foo` extension.
 *
 * This is called by Phosphide after the extension is loaded
 * but *only* if/when a matching extension point is available.
 */
function loadFoo(): Promise<IFoo> {
  // ...
}
```

One final convention is the initialization function for a plugin. This function lives in the plugin `main` module and is named `initialize`. It will be called after the plugin is loaded:

```typescript
/**
 * A function invoked when the plugin is loaded.
 *
 * The resolved disposable will be called by Phosphide when the 
 * plugin is unloaded.
 */
function initialize(): Promise<IDisposable> {
  // ...
}
```

An important thing to note is that we have no way to verify that the type provided by an extension matches the type required of the extension point, especially because plugin authors are not required to write TypeScript. We just assume the types are correctly duck-typed.

**Comment by sccolbert** [comment]
If anyone has any particular questions about how things get hooked up, or about how a particular pattern or use case would be expressed, please feel free to ask.

**Comment by blink1073** [comment]
Are we supporting lazy-loading of plugins, or are they all meant to be discovered and loaded at startup?  
If we are using `node_modules`, they are all going to be discovered at startup.  If we want to support delayed loading, we would have to add a `name` or some other identifier to a `Plugin`, and have a whitelist of startup plugins, and then support loading others by identifier.

**Comment by sccolbert** [comment]
The name of a plugin is the name of the package. On startup, we should scan node modules to get the  top-level `package.json` files. Those should be inspected for a `phosphide` key. If it exists, it should be considered a plugin. The app will be started with a list of plugins to load on startup. All others should be dynamically loaded.

The public API to the `phosphide` module should basically be a suite of functions to manage querying/loading/unloading plugins based on package name.

**Comment by blink1073** [comment]
Perfect, exactly what I was thinking.

**Comment by blink1073** [comment]
Another thought: do we allow users to `npm install` new packages while the server is running, and then load those plugins?  There may be potential security concerns.  The current behavior is to load just the `package.json` files for the plugins, and then load plugins explicitly by name as they are required in context.    The list of available plugins is based on steal.js' initial crawl of the `node_modules` directory.

**Comment by Carreau** [comment]
> Another thought: do we allow users to npm install new packages while the server is running, and then load those plugins?

I doubt we can ask user to restart the server, people might have computation that takes hours to complete, and cannot restart the server. 
I'm fine if we don't rescan on each page load, and if user have to actually refresh the page after setting an option though. 

To contradict myself I guess some of current plugins also need python handlers that do require server restart, and people can live with that. But I guess these case are less frequents.

**Comment by sccolbert** [comment]
This is really more of a security point than anything else. Installing new packages would have to be something supported by the server anyway. Probably in the form of a plugin :) The `phosphide` module can expose a function to rescan for new plugins.

**Comment by jdfreder** [comment]
If I'm understanding correctly, I say a definite +1 to the ability to rescan because when we allow kernels to serve static assets, we'll want them to be able to load without restarting the webserver/front-end.

**Comment by ellisonbg** [comment]
Yep, I think that rescanning is pretty important.

On Thu, Oct 22, 2015 at 6:25 PM, Jonathan Frederic <notifications@github.com
> wrote:

> If I'm understanding correctly, I say a definite +1 to the ability to
> rescan because when we allow kernels to serve static assets, we'll want
> them to be able to load without restarting the webserver/front-end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phosphorjs/phosphide/issues/2#issuecomment-150372963>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
A refresh of the page triggers a rescan of `node_modules` (the default behavior of steal.js).

**Comment by sccolbert** [comment]
Refreshing the page can be a can of worms for complex apps. Supporting that seamlessly mean keeping track of **all** application state (including all layout). That (IMO) is not really tractable. We will need a different interface to manually refresh, so we can hook that up to a ui element.

**Comment by blink1073** [comment]
Yep, looking into it now.

**Comment by blink1073** [comment]
Is `location.reload()` acceptable?  https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

**Comment by blink1073** [comment]
I only say that because from reading the API docs and playing with steal.js, I don't see a way to retrigger the reload otherwise.

**Comment by blink1073** [comment]
I pinged the stealjs folks on gitter.

**Comment by sccolbert** [comment]
We won't be able to reload javascript (and don't want to absent a full refresh). We just want to query for new plugins so that we may load the new ones.

**Comment by sccolbert** [comment]
Reloading existing JS will leave the app in a non-deterministic state.

**Comment by blink1073** [comment]
If we are the ones installing the new plugins, we know where to find them, and could manually load them without using the steal.js mechanism.

**Comment by sccolbert** [comment]
yes - but maybe we aren't. Someone could conceivably install a plug from a terminal (on a local machine). We would need to manually scan there. Basically, all we need in `phosphide` is a function called `scanForPlugins` which updates its internal set with newly added plugins. An in-app package manager can just use that API.

**Comment by jasongrout** [comment]
If we install a top-level package, we know where that is.  But what about that top-level package then using some of its dependencies, and those dependencies using their dependencies?  Stealjs would normally know where to load things because it has scanned the entire tree.  I think we need to trigger such a rescan of the package.json files.

**Comment by jasongrout** [comment]
Chris brought up that stealjs may not scan everything at the start.  I thought it did.  I'll check.

**Comment by blink1073** [comment]
The `steal.js` folks gave us a method to manually trigger the npm traversal.  How about modifying `listPlugins` like this?  `function listPlugins(reload = false): Promise<string[]>;`?

**Comment by sccolbert** [comment]
Sounds reasonable. Take some liberties with what you think is the proper API for now, and we can review in detail next week.

**Comment by blink1073** [comment]
I have a working demo using `steal.js` and the plugin scheme outlined [above](https://github.com/phosphorjs/phosphide/issues/2#issuecomment-149276041): https://github.com/blink1073/phosphide-demo-app.

**Comment by jasongrout** [comment]
By the way, steal does have an issue for progressively loading package.json: https://github.com/stealjs/system-npm/issues/41

**Comment by ellisonbg** [comment]
This is looking really great. Haven't had a chance to dig into all the
details, but the code is really transparent and simple.

On Sat, Oct 24, 2015 at 2:22 PM, Jason Grout <notifications@github.com>
wrote:

> By the way, steal does have an issue for progressively loading
> package.json: stealjs/system-npm#41
> <https://github.com/stealjs/system-npm/issues/41>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phosphorjs/phosphide/issues/2#issuecomment-150839394>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
A few proposed changes:

- Allow extension points and extensions to be in separate modules so they can be lazily loaded.
-  Initializer function for the plugin must be declared.
-  Allow a fallback to the `package.json` "main" entry point.


```typescript
export
interface IPluginJSON {
  /**
   * The path to the "main" javascript file for the plugin.
   *
   * This path is relative to the `package.json`.
   *
   * If not given, it will default to the top-level `package.json` main.
   */
  main?: string;

  /**
   * The name of the initialization function in the plugin `main` module.
   *
   * When the extension is loaded, this function will be called to
   * return a Disposable object.
   */
  initializer?: string;

  /**
   * The extension points provided by the plugin.
   *
   * Other plugins may contribute extensions to these extension points.
   */
  extensionPoints?: IExtensionPointJSON[];

  /**
   * The extensions provided by the plugin.
   *
   * These are contributions to extension points of other plugins.
   */
  extensions?: IExtensionJSON[];
}

export
interface IExtensionJSON {
  /**
   * The id of the extension point to which the extension contributes.
   */
  point: string;

  /**
   * The name of the loader function in the plugin `main` module.
   *
   * When the extension is loaded, this function will be called to
   * return a Promise which resolves to the actual extension object
   * to contribute to the extension point.
   */
  loader?: string;

  /**
   * The path to the JSON data file for the extension.
   *
   * Some extension points (like menus and keymaps) can make use of
   * data defined as JSON. This path will be used to load the JSON
   * and provide it to the extension point.
   */
  data?: string;

  /**
   * Extra configuration data for the extension.
   *
   * Some extension points can make use of extra static declarative
   * data associated with an extension. That data goes here in the
   * form of a JSON object.
   */
  config?: any;

  /**
   * The path to the "main" javascript file for the extension.
   *
   * This path is relative to the `package.json`.
   *
   * If not given, it will default to plugin main file.
   */
   main?: string;
}


export
interface IExtensionPointJSON {
  /**
   * The unique id of the extension point.
   *
   * This should be namespaced: "my-plugin:extension-point-name".
   */
  id: string;

  /**
   * The name of the receiver function in the plugin `main` module.
   *
   * When an extension is loaded for this extension point, this
   * function will be invoked with an `IExtension` object.
   */
  receiver: string;

  /**
   * The path to the "main" javascript file for the extension point.
   *
   * This path is relative to the `package.json`.
   *
   * If not given, it will default to plugin main file.
   */
   main?: string;
}
```

**Comment by sccolbert** [comment]
What about adding an optional initializer to the extensions/extensionpoints as well?

**Comment by sccolbert** [comment]
Initializers return `Promise<IDisposable>`

**Comment by blink1073** [comment]
Updated, and renamed `main` -> `module`.
