### ISSUE TITLE
Plugin Reloading Semantics

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphide#4]
We need to think about how to handle re-loading plugins.  If the underlying plugin has not changed, it will not load any additional JS onto the page, but if it has, we would end up with two versions of the same JS.  Some web searching shows that it is not really possible to "remove" JS once it has been loaded.

We could blacklist modules that have already been loaded once, and require a server restart to get a new version.

Also, what happens if you actually update a plugin version and then a new plugin requires that version?

**Comment by matthewp** [comment]
If this has anything to do with Steal you can remove modules that have been loaded using System.delete(name).  Sorry if I'm out of bounds here.

**Comment by blink1073** [comment]
Hi Matt, thanks for chiming in.  I tried `System.delete('foo');`, then altered `foo/index.js`, then tried `System.import('foo')` and got the original module back (with no hit to the server), is there something I'm missing?

**Comment by matthewp** [comment]
So you're probably getting the module name wrong which happens because module names are weird. If you are using Steal >= 0.12 you can see all of the names by looking at System._traceData.loads in your console. Using the npm plugin you probably have a name like `package@version#path`.  You should be able to take a friendly name and get the real module name by doing:

```
System.normalize("foo").then(function(name){
  System.delete(name);
});
```

Normalize takes a second argument which is the parentName, the name of the module that is doing the importing. Depending on what you are trying to do, that argument may be needed or may not be needed.

**Comment by matthewp** [comment]
Not sure what you are wanting to do... if a plugin is a package (I think it is?) then you probably want to delete the entire package, no? So once you find the name of the package's main you can traverse through all of the children and delete them. Something like:

```js
function deleteEntirePackage(name) {
  if(System.has(name)) {
    var deps = System.getDependencies(name);
    System.delete(name);

    deps.forEach(deleteEntirePackage);
  }
}

deleteEntirePackage("foo@1.0.0#main")
```

**Comment by blink1073** [comment]
Sweet, verified that normalize/delete/import does what I expect.

**Comment by blink1073** [comment]
That's tricky, because the children might be shared with another plugin.

**Comment by matthewp** [comment]
You could also use `System.getDependants(name)` to get all of the dependant (parent) modules, and you could use that to check if they are shared.

**Comment by blink1073** [comment]
Yep, certainly doable, but we also have to consider things like co-dependent module state.

**Comment by sccolbert** [comment]
This sounds like a can of worms. It may not be feasible to reload a plugin once it's already loaded. Perhaps we should focus on only loading newly installed plugins.

**Comment by jasongrout** [comment]
+1 on putting reload on hold.
