### ISSUE TITLE
Shortcut Manager Corrections

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphide#50]
@dwillmer @afshin 

Is ShortcutRegistry a better name for this class/interface?

What is this used for without also passing `args`? Can we remove it and just use `get`?
https://github.com/phosphorjs/phosphide/blob/master/src/shortcutmanager/index.ts#L72

Some unused imports here:
https://github.com/phosphorjs/phosphide/blob/master/src/shortcutmanager/plugin.ts#L21

This method should be a free function:
https://github.com/phosphorjs/phosphide/blob/master/src/shortcutmanager/plugin.ts#L149

This method is not used anywhere:
https://github.com/phosphorjs/phosphide/blob/master/src/shortcutmanager/plugin.ts#L166

This needs to be implemented:
https://github.com/phosphorjs/phosphide/blob/master/src/shortcutmanager/plugin.ts#L111

Should provide a signal to notify when shortcuts are added/removed:
https://github.com/phosphorjs/phosphide/blob/master/src/shortcutmanager/plugin.ts#L45

**Comment by afshin** [comment]
> Is ShortcutRegistry a better name for this class/interface?

I have no opinion about which is a better name, because we're using a menu manager and a command registry and both seem reasonable to me.
