### ISSUE TITLE
Document Plugin Creation Process

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphide#75]
- [Extensions](https://github.com/phosphorjs/phosphide/blob/master/src/core/extensionregistry.ts#L19) add content to the [application](https://github.com/phosphorjs/phosphide/blob/master/src/core/application.ts) itself or to services.
- An example extension is the [command palette](https://github.com/phosphorjs/phosphide/blob/master/src/core/serviceregistry.ts#L27).
- Extensions are activated explicitly through the Application [instance](https://github.com/phosphorjs/phosphide/blob/master/src/core/application.ts#L71). 
- The extensions provided to app on startup, are activated automatically

- [Services](https://github.com/phosphorjs/phosphide/blob/master/src/core/serviceregistry.ts) provide functionality to other parts of the application.
- An example service is the [palette registry](https://github.com/phosphorjs/phosphide/blob/master/src/services/paletteregistry.ts), which is used by the application itself and provided as its `palette` attribute as a convenience to add items to the command palette.
- Services are activated on-demand.

- A full working example is contained  [here](https://github.com/phosphorjs/phosphide/tree/master/example).

**Comment by jasongrout** [comment]
Thanks!

**Comment by blink1073** [comment]
Relevant classes (with inline API docs):
https://github.com/phosphorjs/phosphide/blob/master/src/core/application.ts
https://github.com/phosphorjs/phosphide/blob/master/src/core/extensionregistry.ts#L19
https://github.com/phosphorjs/phosphide/blob/master/src/core/serviceregistry.ts#L27

services are activated on-demand. Extensions are activated explicitly through the Application [instance](https://github.com/phosphorjs/phosphide/blob/master/src/core/application.ts#L71)
The extensions provided to app on startup, are activated automatically

**Comment by blink1073** [comment]
A phosphide application is comprised of Providers and Extensions.

A service provider is used by extensions to add functionality to the
application.  Example services include the command palette and
the application shell.  Service providers can `require` other services.
Services are activated when they are needed by other services or extensions.

```typescript

/**
 * A log service provider.  The public interface of the service to the
 * application.
 */
export
const logServiceProvider = {
  id: 'example.services.logService',
  provides: LogRegistry,
  resolve: () => new LogRegistry()
};


/**
 * A registry for loggers.  The concrete object passed to service consumers.
 */
export
class LogRegistry {
  /**
   * List of the names of existing loggers.
   */
  list(): string[] {
    return Object.keys(this._loggers);
  }

  /**
   * Test whether the registery contains a logger.
   */
  has(logger: string): boolean {
    return logger in this._loggers;
  }

  /**
   * Create a named logger.
   */
  create(name: string): void {
    this._loggers.set(name, (msg) => { console.log(name, msg); });
  }

  /**
   * Log a command with a given logger.
   */
  log(name: string, msg: string): void {
    let logger = this._loggers.get(name);
    if (logger) logger(msg);
  }

  private _loggers = new Map<string, (msg: string) => void>();
}
```

Extensions use services, including the Application object itself,
to provide functionality to the application.  Extensions provided to
the application are activated immediately.  Activations added later 
can be activated by id.


```typescript
import { Application } from 'phosphide/lib/core/application';

import { LogRegistry } from './logger';


export
const fooExtension = {
  id: 'example.extensions.foo',
  requires: [LogRegistry],
  activate: activateFoo
}


// Function which activates the `foo` extension.
// It is called when all of the `requires` objects are available,
// with the Application object as the first argument and the remaining
// required services in order.
function activateFoo(app: Application, registry: LogRegistry): Promise<void> {
  // Use the log registry provider.
  registry.create('foo');

  // Use the commands service provided on the application object.
  app.commands.add([
    { id: 'example:log-foo', handler: logFoo }
  ]);

  // Use the command palette service on the application object.
  app.palette.add([
    { id: 'example:log-foo', text: 'Log Foo' }
  ])

  // Handle `example:log-foo` command invocations.
  function logFoo(): void {
    registry.log('foo', 'hello, world!');
  }

  return Promise.resolve<void>();
}
```

**Comment by basarat** [comment]
> A full working example is contained here.

Can I view/test it online?

**Comment by blink1073** [comment]
Hi @basarat!  We don't have the current example online, but a previous iteration is here: http://phosphorjs.github.io/phosphide-example/.  The end result is the same, but we have since changed the way plugins are defined.

**Comment by blink1073** [comment]
See the readme [here](https://github.com/jupyter/jupyter-js-plugins) for what it looks like in the context of JupyterLab.

**Comment by basarat** [comment]
Thanks! :rose:

**Comment by blink1073** [comment]
Migrated to https://github.com/phosphorjs/phosphor/issues/103
