### ISSUE TITLE
Link in README to API docs directs to not found

### ISSUE THREAD

**Issue by willingc** [phosphorjs/phosphide#76]
http://phosphorjs.github.io/phosphide/api/

**Comment by blink1073** [comment]
It appears the `gh-pages` branch was deleted, so the docs are not getting pushed:

https://travis-ci.org/phosphorjs/phosphide/builds/117527792#L720

**Comment by sccolbert** [comment]
This should be fixed (https://travis-ci.org/phosphorjs/phosphide/builds/118519410). The changes should propagate to pages in a few minutes.

**Comment by blink1073** [comment]
Verified, thanks for the kick @willingc!

**Comment by willingc** [comment]
:surfer:
